apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kubecost-operator.v0.0.2
  namespace: kubecost
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: cost management for kubernetes
  displayName: kubecost
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubecost
  - cost0model
  links:
  - name: Kubecost Operator
    url: https://kubecost-operator.domain
  maturity: alpha
  minKubeVersion: 1.16.0
  provider:
    name: Kubecost
    url: www.kubecost.com
  version: 0.0.2
