apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kubecost-operator.v0.0.2
  namespace: kubecost
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: cost management for kubernetes
  displayName: kubecost
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubecost
  - cost0model
  links:
  - name: Kubecost Operator
    url: https://kubecost-operator.domain
  maturity: alpha
  minKubeVersion: 1.16.0
  provider:
    name: Kubecost
    url: www.kubecost.com
  version: 0.0.2
  relatedImages:
  - name: cost-analyzer-frontend
    image: gcr.io/kubecost1/frontend@sha256:45125a6df7daa330209ea9f26cbe48405595962d3eac799583c4e08ba853f20c
  - name: cost-model
    image: gcr.io/kubecost1/cost-model@sha256:74ff30f7b9bd7c48c345e703999b1d119fae7cac8d4098eba68d9812aae8b908
    name: prometheus
    image: registry.access.redhat.com/openshift3/prometheus@sha256:cc82e7c85f816a0ab6109dc0ee2bd587db3859450bf10e2d3b9241cf5daee233
